;-- DasH - mod --
;-- Developed by Jam3sn - http://jam3sn.deviantart.com --
;-- Edited by borsTiHD - http://p3r0.deviantart.com --

[Rainmeter]
Update=500

[Metadata]
Author=Jam3sn / borsTiHD
Description=System Monitor resource.
License=Creative Commons Attribution 4.0 International
Version=1.0.0

[Variables]
;--Fonts--
Font=GeosansLight

;--Colors---
teal500=0,150,136
teal900=0,77,64

amber900=255,111,0
amber500=255,193,7

cyan500=0,188,212
cyan900=0,96,100

grey50=250,250,250
grey200=238,238,238

grey900=33,33,33,100

;-- USER OPTIONS --
textColor=#grey50#
highlightColor=#teal500#
dataColor=#teal900#
bgColor=#grey900#
pingURL="www.google.com"

;-- DISK NAMES --
D1=C:
D2=D:
D3=E:
D4=F:

;-- Measures --
[Measure12HrTime]
Measure=Time
Format=%I:%M

[MeasureDate]
Measure=Time
Format="%a %d %b"

[MeasureVolume]
Measure=Plugin
Plugin=Win7AudioPlugin

[MeasureCPU]
Measure=CPU
Processor=0
UpdateDivider=2

[MeasureRAM]
Measure=PhysicalMemory
UpdateDivider=2

[MeasureIP]
Measure=Plugin
Plugin=SysInfo
SysInfoType=IP_ADDRESS

[MeasureGetExIP]
Measure=WebParser
URL=https://api.ipify.org/
RegExp=(?s)(.*)
UpdateRate=3600

[MeasureExIP]
Measure=WebParser
URL=[MeasureGetExIP]
StringIndex=1

[MeasureIn]
Measure=NetIn

[MeasureOut]
Measure=NetOut

[MeasurePing]
Measure=Plugin
Plugin=PingPlugin
DestAddress=#pingURL#

[MeasureDrive1]
Measure=FreeDiskSpace
Drive=#D1#
InvertMeasure=1

[MeasureDrive2]
Measure=FreeDiskSpace
Drive=#D2#
InvertMeasure=1

[MeasureDrive3]
Measure=FreeDiskSpace
Drive=#D3#
InvertMeasure=1

[MeasureDrive4]
Measure=FreeDiskSpace
Drive=#D4#
InvertMeasure=1

[MeasureUptime]
Measure=Uptime
Format="%4!2i! d, %3!02i! h, %2!02i! m"

;-- Meters --

;-- 1st Cell --------------------------------------------------

[BackgroundCard]
Meter=Image
H=1040
W=300
X=0
Y=0
SolidColor=#bgColor#

[TimeDisplay]
Meter=String
MeasureName=Measure12HrTime
FontColor=#textColor#
FontSize=36
FontFace=#Font#
X=150
Y=15
Text="%1"
AntiAlias=1

[DateDisplay]
Meter=String
MeasureName=MeasureDate
FontColor=#textColor#
FontSize=16
FontFace=#Font#
X=20
Y=39
Text="%1"
AntiAlias=1

[Volume]
Meter=Bar
MeasureName=MeasureVolume
BarOrientation=Horizontal
BarColor=#highlightColor#
H=20
W=150
X=75
Y=100
AntiAlias=1
SolidColor=#textColor#

[VolumeUp]
Meter=String
X=227
Y=85
AntiAlias=1
Text="+"
FontColor=#textColor#
FontFace=#Font#
FontSize=30
LeftMouseDownAction=[!CommandMeasure MeasureVolume "ChangeVolume +5"][!Redraw]

[VolumeDown]
Meter=String
X=45
Y=85
AntiAlias=1
Text="-"
FontColor=#textColor#
FontFace=#Font#
FontSize=30
LeftMouseDownAction=[!CommandMeasure MeasureVolume "ChangeVolume -5"][!Redraw]

[VolumeUnmute]
Meter=Image
ImageName=./@Resources/Unmuted.png
H=19
W=19
X=20
Y=100
AntiAlias=1
PreserveAspectRatio=1
LeftMouseDownAction=[!CommandMeasure MeasureVolume "ToggleMute"][!ShowMeter VolumeMute][!HideMeter VolumeUnmute][!Redraw]

[VolumeMute]
Meter=Image
ImageName=./@Resources/Mute.png
Hidden=1
H=19
W=19
X=20
Y=100
AntiAlias=1
PreserveAspectRatio=1
LeftMouseDownAction=[!CommandMeasure MeasureVolume "ToggleMute"][!ShowMeter VolumeUnmute][!HideMeter VolumeMute][!Redraw]

[Line1]
Meter=Image
SolidColor=#highlightColor#
W=300
H=1
X=0
Y=50r
AntiAlias=1

;-- 2nd Cell --------------------------------------------------

[CpuMeter]
Meter=Bar
MeasureName=MeasureCPU
BarOrientation=Horizontal
BarColor=#highlightColor#
H=20
W=150
X=75
Y=30r
AntiAlias=1
SolidColor=#textColor#

[CpuGraph]
Meter=Line
MeasureName=MeasureCPU
LineColor=#dataColor#
H=20
W=150
X=75
Y=0r
AntiAlias=1

[CpuLabel]
Meter=String
X=20
Y=0r
Text="CPU"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[CpuPercentage]
Meter=String
MeasureName=MeasureCPU
X=280
Y=0r
StringAlign=Right
Text="%1%"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[RamMeter]
Meter=Bar
MeasureName=MeasureRAM
BarOrientation=Horizontal
BarColor=#highlightColor#
H=20
W=150
X=75
Y=40r
AntiAlias=1
SolidColor=#textColor#

[RamGraph]
Meter=Line
MeasureName=MeasureRAM
LineColor=#dataColor#
H=20
W=150
X=75
Y=0r
AntiAlias=1

[RamLabel]
Meter=String
X=20
Y=0r
Text="RAM"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[RamPercentage]
Meter=String
MeasureName=MeasureRAM
Percentual=1
X=280
Y=0r
StringAlign=Right
Text="%1%"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Line2]
Meter=Image
SolidColor=#highlightColor#
W=300
H=1
X=0
Y=50r
AntiAlias=1

;-- 3rd Cell --------------------------------------------------

[LocalIPLabel]
Meter=String
X=20
Y=30r
Text="Local IP"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[LocalIP]
Meter=String
MeasureName=MeasureIP
X=280
Y=0r
StringAlign=Right
Text="%1"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[ExIPLabel]
Meter=String
X=20
Y=40r
Text="External IP"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[ExIP]
Meter=String
MeasureName=MeasureExIP
X=280
Y=0r
StringAlign=Right
Text="%1"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[DownloadLabel]
Meter=String
X=20
Y=60r
Text="Download"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[DownloadLine]
Meter=Line
MeasureName=MeasureIn
LineColor=#highlightColor#
H=20
W=125
X=155
Y=0r
AntiAlias=1

[UploadLabel]
Meter=String
X=20
Y=40r
Text="Upload"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[UploadLine]
Meter=Line
MeasureName=MeasureOut
LineColor=#highlightColor#
H=20
W=125
X=155
Y=0r
AntiAlias=1

[PingLabel]
Meter=String
X=20
Y=60r
Text="Ping"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Ping]
Meter=String
MeasureName=MeasurePing
X=280
Y=0r
StringAlign=Right
Text="%1 MS"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Line3]
Meter=Image
SolidColor=#highlightColor#
W=300
H=1
X=0
Y=50r
AntiAlias=1

;-- 4th Cell --------------------------------------------------

;-- DRIVE 1 --
[Drive1Meter]
Meter=Bar
MeasureName=MeasureDrive1
BarOrientation=Horizontal
BarColor=#highlightColor#
H=20
W=150
X=75
Y=30r
AntiAlias=1
SolidColor=#textColor#

[Drive1Label]
Meter=String
X=20
Y=0r
Text=#D1#\
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive1Percentage]
Meter=String
MeasureName=MeasureDrive1
Percentual=1
X=280
Y=0r
StringAlign=Right
Text="%1%"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive1GB]
Meter=String
MeasureName=MeasureDrive1
FontColor=#dataColor#
H=20
W=150
X=77
Y=3r
AntiAlias=1
Text="%1GB"
NumOfDecimals=2
Scale=1073741824

;-- DRIVE 2 --
[Drive2Meter]
Meter=Bar
MeasureName=MeasureDrive2
BarOrientation=Horizontal
BarColor=#highlightColor#
H=20
W=150
X=75
Y=40r
AntiAlias=1
SolidColor=#textColor#

[Drive2Label]
Meter=String
X=20
Y=0r
Text=#D2#\
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive2Percentage]
Meter=String
MeasureName=MeasureDrive2
Percentual=1
X=280
Y=0r
StringAlign=Right
Text="%1%"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive2GB]
Meter=String
MeasureName=MeasureDrive2
FontColor=#dataColor#
H=20
W=150
X=77
Y=3r
AntiAlias=1
Text="%1GB"
NumOfDecimals=2
Scale=1073741824

;-- DRIVE 3 --
[Drive3Meter]
Meter=Bar
MeasureName=MeasureDrive3
BarOrientation=Horizontal
BarColor=#highlightColor#
H=20
W=150
X=75
Y=40r
AntiAlias=1
SolidColor=#textColor#

[Drive3Label]
Meter=String
X=20
Y=0r
Text=#D3#\
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive3Percentage]
Meter=String
MeasureName=MeasureDrive3
Percentual=1
X=280
Y=0r
StringAlign=Right
Text="%1%"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive3GB]
Meter=String
MeasureName=MeasureDrive3
FontColor=#dataColor#
H=20
W=150
X=77
Y=3r
AntiAlias=1
Text="%1GB"
NumOfDecimals=2
Scale=1073741824

;-- DRIVE 4 --
[Drive4Meter]
Meter=Bar
MeasureName=MeasureDrive4
BarOrientation=Horizontal
BarColor=#highlightColor#
H=20
W=150
X=75
Y=40r
AntiAlias=1
SolidColor=#textColor#

[Drive4Label]
Meter=String
X=20
Y=0r
Text=#D4#\
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive4Percentage]
Meter=String
MeasureName=MeasureDrive4
Percentual=1
X=280
Y=0r
StringAlign=Right
Text="%1%"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Drive4GB]
Meter=String
MeasureName=MeasureDrive4
FontColor=#dataColor#
H=20
W=150
X=77
Y=3r
AntiAlias=1
Text="%1GB"
NumOfDecimals=2
Scale=1073741824

[Line4]
Meter=Image
SolidColor=#highlightColor#
W=300
H=1
X=0
Y=50r
AntiAlias=1

;-- 5th Cell --------------------------------------------------

[UptimeLabel]
Meter=String
X=20
Y=30r
Text="Uptime"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1

[Uptime]
Meter=String
MeasureName=MeasureUptime
X=280
Y=0r
StringAlign=Right
Text="%1"
FontColor=#textColor#
FontFace=#Font#
FontSize=16
AntiAlias=1